 
# [0] 
ParkingData: &ParkingData 
  path:  'bparkProductionV3/ParkingBPH1_Run2018B-05May2019-v2_MINIAOD_v1_generationForBParking' 
  files: 'output_*.root' 
  xs:   null 
  model_param: 
    m:    null 
    ctau: null 
    xiO:  null 
    xiL:  null 
  force_xs: false 
  isMC:     false 
  maxevents_scale: 1.0 
 
