 
# [0] 
ParkingData: &ParkingData 
  path: 'bparkProductionV3/ParkingBPH1_Run2018C-05May2019-v1_MINIAOD_v1_generationForBParking/output_*.root' 
  xs:   null 
  model_param: 
    m:    null 
    ctau: null 
    xiO:  null 
    xiL:  null 
  force_xs: false 
  isMC:     false 
  maxevents_scale: 1.0 
 
