 
# [0] 
HiddenValley_vector_m_2_ctau_10_xiO_1_xiL_1: &HiddenValley_vector_m_2_ctau_10_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_2_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    2 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [1] 
HiddenValley_vector_m_2_ctau_50_xiO_1_xiL_1: &HiddenValley_vector_m_2_ctau_50_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_2_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    2 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [2] 
HiddenValley_vector_m_2_ctau_100_xiO_1_xiL_1: &HiddenValley_vector_m_2_ctau_100_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_2_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    2 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [3] 
HiddenValley_vector_m_2_ctau_500_xiO_1_xiL_1: &HiddenValley_vector_m_2_ctau_500_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_2_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    2 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [4] 
HiddenValley_vector_m_5_ctau_10_xiO_1_xiL_1: &HiddenValley_vector_m_5_ctau_10_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_5_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    5 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [5] 
HiddenValley_vector_m_5_ctau_50_xiO_1_xiL_1: &HiddenValley_vector_m_5_ctau_50_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_5_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    5 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [6] 
HiddenValley_vector_m_5_ctau_100_xiO_1_xiL_1: &HiddenValley_vector_m_5_ctau_100_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_5_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    5 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [7] 
HiddenValley_vector_m_5_ctau_500_xiO_1_xiL_1: &HiddenValley_vector_m_5_ctau_500_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_5_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    5 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [8] 
HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1: &HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_10_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [9] 
HiddenValley_vector_m_10_ctau_50_xiO_1_xiL_1: &HiddenValley_vector_m_10_ctau_50_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_10_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [10] 
HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1: &HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_10_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [11] 
HiddenValley_vector_m_10_ctau_500_xiO_1_xiL_1: &HiddenValley_vector_m_10_ctau_500_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_10_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    10 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [12] 
HiddenValley_vector_m_15_ctau_10_xiO_1_xiL_1: &HiddenValley_vector_m_15_ctau_10_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_15_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [13] 
HiddenValley_vector_m_15_ctau_50_xiO_1_xiL_1: &HiddenValley_vector_m_15_ctau_50_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_15_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [14] 
HiddenValley_vector_m_15_ctau_100_xiO_1_xiL_1: &HiddenValley_vector_m_15_ctau_100_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_15_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [15] 
HiddenValley_vector_m_15_ctau_500_xiO_1_xiL_1: &HiddenValley_vector_m_15_ctau_500_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_15_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    15 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [16] 
HiddenValley_vector_m_20_ctau_10_xiO_1_xiL_1: &HiddenValley_vector_m_20_ctau_10_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_20_ctau_10_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 10 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [17] 
HiddenValley_vector_m_20_ctau_50_xiO_1_xiL_1: &HiddenValley_vector_m_20_ctau_50_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_20_ctau_50_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 50 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [18] 
HiddenValley_vector_m_20_ctau_100_xiO_1_xiL_1: &HiddenValley_vector_m_20_ctau_100_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_20_ctau_100_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 100 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
# [19] 
HiddenValley_vector_m_20_ctau_500_xiO_1_xiL_1: &HiddenValley_vector_m_20_ctau_500_xiO_1_xiL_1 
  path:  'bparkProductionV3/HiddenValley_vector_m_20_ctau_500_xiO_1_xiL_1_privateMC_11X_NANOAODSIM_v3_generationForBParking' 
  files: 'output_*.root' 
  xs:   1.0 # [pb] 
  model_param: 
    m:    20 
    ctau: 500 
    xiO:  1 
    xiL:  1 
  force_xs: true 
  isMC:     true 
  maxevents_scale: 1.0 
 
