# Peakfit steering code
#
# Remember that yaml scientific notation requires 1.0 (dots)
# and (+) and (-) for the exponent (e.g. 1.0e+8)
#
# m.mieskolainen@imperial.ac.uk, 2022

path:     '/home/user/fitdata/flat/muon/generalTracks/JPsi'
fitrange: [2.9, 3.3] # GeV

fit:

  S:
    func:    'CB_asym_RBW_conv_pdf'
    w_start:  1
    w_limit:  [0.01, 1.0e+8]
    w_fixed:  False

    p_name:   ['M0', 'sigma', 'n', 'alpha', 'width', 'asym']
    p_start:  [3.097, 0.05, 1.001, 0.5, 9.32e-05, -0.01]
    p_limit:  [[3.085, 3.105], [1.0e-3, 0.3], [1.0001, 10.0], [0.1, 3.0], [1.0e-9, 1.0e-1], [-8.0, 0.0]]
    p_fixed:  [False, False, False, False, False, False]
    
  B:
    func:    'exp_pdf'
    w_start:  1
    w_limit:  [0.01, 1.0e+8]
    w_fixed:  False

    p_name:   ['lambda']
    p_start:  [1.5]
    p_limit:  [[0.01, 2.5]]
    p_fixed:  [False]

  # Add here more fit functions in superposition, by giving a unique string label
  # ...


# Fit algorithm parameters
techno:
  losstype: 'chi2'       # 'chi2' or 'nll'
  use_limits: True       # Use parameter bounds

  ncall_simplex: 200000  # Number of Nelder-Mead simplex search (from Scipy) calls
  ncall_gradient: 10000  # Number of Minuit gradient search calls

  hesse: True      # Minuit HESSE uncertainties
  minos: True      # Minuit MINOS uncertainties

  max_chi2: 1000   # Maximum chi2/ndf for a succesful fit
  max_trials: 1    # Number of restarts
  min_count: 2     # Minimum number of entries in the histogram

  strategy: 0      # Minuit parameters
  tol: 1.0e-8

