# Peakfit steering code
#
# Remember that yaml scientific notation requires 1.0 (dots)
# and (+) and (-) for the exponent (e.g. 1.0e+8)
#
# m.mieskolainen@imperial.ac.uk, 2022

path:     '/home/user/fitdata/flat/muon/generalTracks/JPsi'
fitrange: [2.9, 3.3] # GeV
losstype: 'chi2' # 'chi2' or 'nll'


fit:

  S:
    func:    'CB_RBW_conv_pdf'
    w_start:  1
    w_limit:  [0.01, 1.0e+8]

    p_name:   ['M0', 'sigma', 'n', 'alpha', 'width', 'asym']
    p_start:  [3.09, 0.05, 1.001, 0.5, 9.32e-05, -0.01]
    p_limit:  [[3.085, 3.105], [1.0e-3, 0.3], [1.0001, 10.0], [0.1, 3.0], [1.0e-9, 1.0e-1], [-8.0, 0.0]]

  B:
    func:    'exp_pdf'
    w_start:  1
    w_limit:  [0.01, 1.0e+8]

    p_name:   ['lambda']
    p_start:  [1.5]
    p_limit:  [[0.01, 2.5]]

  # Add here more fit functions in superposition, by giving a unique string label
  # ...



