# Peakfit steering code
#
# Remember that yaml scientific notation requires 1.0 (dots)
# and (+) and (-) for the exponent (e.g. 1.0e+8)
#
#
# Tips: One can simplify the model by settings some parameters to
# their "symmetric" (e.g. 0) values and fixing those.
#
# m.mieskolainen@imperial.ac.uk, 2023

path:     './travis-stash/input/icefit/dqcd_2018_test/flat/muon/generalTracks/JPsi'
years:    [2018] #[2016, 2017, 2018]

fitrange: [2.85, 3.35] # Nominal fit window (GeV)

# List of systematic variations active (note that the SYMMETRIC-SIGNAL works only with particular signal PDF)
systematics: ['DEFAULT', 'MASS-WINDOW-DOWN', 'MASS-WINDOW-UP']


fit:

  S:
    func:    'DSCB_pdf'
    args:
      norm:     True
    
    # Function weight (fit contribution) parameter
    w_start:  100.0
    w_limit:  [1.0e-4, 1.0e+5]
    w_fixed:  False
    
    p_name:   ['M0', 'sigma', 'n_low', 'alpha_low', 'n_high', 'alpha_high']
    p_start:  [3.097, 0.03, 1.5, 1.1, 1.5, 1.1]
    p_limit:  [[3.085, 3.12], [0.01, 0.05], [1.001, 100.0], [0.001, 3.0], [1.001, 100.0], [0.001, 3.0]]
    p_fixed:  [False, False, False, False, False, False]
  
  B:
    func:    'exp_pdf'
    args:
      norm:     True
      #Nmin:     null # not active
    
    # Function weight (fit contribution) parameter
    w_start:  1.0e-3
    w_limit:  [1.0e-4, 1.0e+5]
    w_fixed:  False

    p_name:   ['lambda']
    p_start:  [1.0e-4]
    p_limit:  [[1.0e-5, 4.0]]
    p_fixed:  [False]


  # Add here more fit components in linear superposition, by giving a unique string label
  # ...


# Fit algorithm parameters
techno:
  losstype: 'nll'               # 'chi2', 'nll' or 'wasserstein'
  use_limits: True              # Use parameter bounds
  zerobin: 1.0e-2               # Minimum number of counts in a valid bin
  
  # Use enough calls / iterations (otherwise can get stuck in bad local minima)
  
  ncall_scipy_simplex: 0           # Number of scipy search calls
  ncall_mystic_diffev2:     1      # Number of Mystic solver calls
  ncall_mystic_fmin_powell: 1      # Number of Mystic solver calls

  ncall_minuit_scan:     0         # Number of brute force 1D-scan calls
  ncall_minuit_simplex:  0         # Number of Nelder-Mead simplex search calls
  ncall_minuit_gradient: 10000     # Number of Minuit gradient search calls
  
  minos: True       # If True, Minuit MINOS uncertainties (slower but best), otherwise HESSE

  max_chi2: 1200    # Maximum chi2/ndf for a succesful fit
  min_count: 5      # Minimum number of entries in the histogram
  max_trials: 3     # Number of restarts

  set_to_nan: True  # Set parameters after the fit to NaN if not passing max_chi2 or min_count

  strategy: 1       # Default 1
  tol: 0.1          # Default 0.1, https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.tol
