# Peakfit steering code
#
# Remember that yaml scientific notation requires 1.0 (dots)
# and (+) and (-) for the exponent (e.g. 1.0e+8)
#
# m.mieskolainen@imperial.ac.uk, 2022

path:     '/home/user/fitdata/flat/muon/generalTracks/JPsi'
fitrange: [2.9, 3.3] # GeV

fit:

  S:
    func:    'CB_asym_RBW_conv_pdf'
    args:    
      norm:     True
      Nmin:     256 # minimum number of function samples for convolution integral
      xfactor:  0.2 # extra domain extension factor for convolution integral (0.2 gives 20%)

    w_start:  10.0
    w_limit:  [0.001, 1.0e+8]
    w_fixed:  False

    # Gamma(J/psi) = 9.32e-05 GeV (very narrow!)
    # CB_param   = par[0],par[1],par[2],par[3] ~ Crystal-Ball detector smearing
    # aRBW_param = par[0],par[4],par[5]        ~ J/Psi resonance ~ [initial state pdf x form factor x breit-wigner x radiative]

    p_name:   ['M0', 'sigma', 'n', 'alpha', 'Gamma', 'asym']
    p_start:  [3.097, 0.02, 1.001, 1.3, 1.0e-4, -0.01]
    p_limit:  [[3.085, 3.1], [0.01, 0.05], [1.0001, 2.0], [0.1, 2.0], [9.32e-5, 0.05], [-10.0, 10.0]]
    p_fixed:  [False, False, False, False, False, False]
    
  B:
    func:    'exp_pdf'
    args:
      norm:     True
      #Nmin:     null # not active
    
    w_start:  10.0
    w_limit:  [0.001, 1.0e+8]
    w_fixed:  False

    p_name:   ['lambda']
    p_start:  [0.01]
    p_limit:  [[1.0e-5, 4.0]]
    p_fixed:  [False]


  # Add here more fit components in linear superposition, by giving a unique string label
  # ...


# Fit algorithm parameters
techno:
  losstype: 'nll'              # 'chi2' or 'nll'
  use_limits: True             # Use parameter bounds
  
  ncall_simplex_scipy: 10000   # Number of scipy search calls
  ncall_scan:     100          # Number of brute force scan calls
  ncall_simplex:  10000        # Number of Nelder-Mead simplex search calls
  ncall_gradient: 10000        # Number of Minuit gradient search calls
  
  
  hesse: True       # Minuit HESSE uncertainties
  minos: False      # Minuit MINOS uncertainties

  max_chi2: 600     # Maximum chi2/ndf for a succesful fit
  max_trials: 2     # Number of restarts
  min_count: 5      # Minimum number of entries in the histogram
  
  strategy: 1       # Default 1
  tol: 0.1          # Default 0.1, https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.tol

