## Pure plotting setup

basic:
  active: true
  nbins:  70

contours: 
  active: false

## Binned ROC plots can be 1D or 2D;
# use a running number __0, __1, ... as an identifier for new plots
plot_ROC_binned[0]:
  var:   ['trk_pt']
  edges: [0.5, 0.7, 1.0, 1.25, 1.5, 1.75, 2.5, 4.0, 10, 10000]

plot_ROC_binned[1]:
  var:   ['trk_eta', 'trk_pt']
  edges: [[-2.5, -1.5, -1.15, -0.75, 0.0, 0.75, 1.15, 1.5, 2.5],
          [0.5, 0.7, 1.0, 1.25, 1.5, 1.75, 2.5, 4.0, 10, 10000]]

## MVA output density (1D)
MVA_output:
  edges: 80

## MVA (output, external variable) density (2D)
#plot_COR[0]:
#  var:   ['']
#  edges: [{'nbin': 50, 'q': [0.0,  1.0],  'space': 'linear'},
#          {'nbin': 50, 'q': [0.0,  0.95], 'space': 'linear'}]

#plot_COR[1]:
#  var:   ['.?hlt_pms2.?']
#  edges: [{'nbin': 30, 'minmax': [0.0, 1.0], 'space': 'linear'},
#          {'nbin': 30, 'q': [0.0, 0.95],     'space': 'log10'}]
