param:
  #active:         ['xgb0'] # Add model identifiers here
  active:         [null]
  num_samples:    5
  max_num_epochs: 50

setup:

  gnn_setup:
    search_algo: 'HyperOpt'

    search_metric:
      metric: 'AUC'
      mode: 'max'
      
    param:
      cdim:
        type: "tune.choice"
        value: [32, 64, 96, 128, 196, 256, 512, 1024]

      global_pool:
        type: "tune.choice"
        value: ['mean', 'max', 'add']

    #  batch_size:
    #    type: "tune.choice"
    #    value: [16, 32, 64, 128]

      lr:
        type: "tune.loguniform"
        value: [1.0E-5, 1.0E-1] # Careful with with .0E (otherwise -> string)
    
    #
    #batch_size:
    #  type: "tune.choice"
    #  value: [32, 64, 128, 256]
    #

    # Add more steers here
    # ...

  xgb_setup:
    search_algo: 'HyperOpt'

    search_metric:
      metric: 'AUC'
      mode: 'max'

    param:
      
      num_boost_round:
        type: "tune.randint"
        value: [20, 120]

      learning_rate:
        type: "tune.uniform"
        value: [0.01, 0.6]
      
      ## Tree parameters
      max_depth:
        type:  "tune.choice"
        value: [4,5,6,7,8,9,10,11,12,13,14,15,16,17]

      ## Regularization
      reg_lambda: # Smoothness
        type: "tune.uniform"
        value: [0.0, 5.0]

      reg_alpha: # Sparsity
        type: "tune.uniform"
        value: [0.0, 0.5]

      ## Tree splitting
      #min_child_weight:
      #  type: "tune.uniform"
      #  value: [0.1, 2.0]  # Between [0, inf] Default 1.0
      
      gamma:
        type: "tune.uniform"
        value: [0.0, 2.0]   # Between [0,inf] Default 1.0
      
      #max_delta_step:
      #  type: "tune.uniform"
      #  value: [0.0, 1.5]  # Between [0, inf] Default 0

      #subsample:
      #  type: "tune.uniform"
      #  value: [0.5, 1]    # Between [0, 1] # Default 1

      colsample_bytree:
        type: "tune.uniform"
        value: [0.3, 1.0] # Between [0,1], default 1

      colsample_bylevel:
        type: "tune.uniform"
        value: [0.3, 1.0] # Between [0,1], default 1

      colsample_bynode:
        type: "tune.uniform"
        value: [0.3, 1.0] # Between [0,1], default 1
