# ========================================================================
## Raytune setup
# ========================================================================

param:
  
  #active:         ['xgb1']
  active:  [null]
  num_samples:    1000
  max_num_epochs: 50 # Keep it high enough if tuning 'num_boost_round' with xgboost

setup:

  xgb_trial_0:
    search_algo: 'HyperOpt'

    search_metric:
      metric: 'AUC'
      mode: 'max'

    param:
      
      num_boost_round:
        type: "tune.randint(20, 400)"
