# --------------------
## Process input

DATAPATH="/home/user/travis-stash/input/icedqcd"

dqcd.py --runmode genesis --inputfiles theory_A_point_ANY.yml --config tune_ANY.yml --datapath $DATAPATH
dqcd.py --runmode genesis --inputfiles theory_A_point_1.yml   --config tune_ANY.yml --datapath $DATAPATH
dqcd.py --runmode genesis --inputfiles theory_A_point_2.yml   --config tune_ANY.yml --datapath $DATAPATH
dqcd.py --runmode genesis --inputfiles theory_A_point_3.yml   --config tune_ANY.yml --datapath $DATAPATH

dqcd.py --runmode genesis --inputfiles theory_A_point_1.yml   --config tune0.yml --datapath $DATAPATH
dqcd.py --runmode genesis --inputfiles theory_A_point_2.yml   --config tune0.yml --datapath $DATAPATH
dqcd.py --runmode genesis --inputfiles theory_A_point_3.yml   --config tune0.yml --datapath $DATAPATH


# --------------------
## Train models

# Theory A: MVA conditionalized on all model points
dqcd.py --runmode train --inputfiles theory_A_point_ANY.yml --config tune_ANY.yml

# Theory A: MVA trained per model point
dqcd.py --runmode train --inputfiles theory_A_point_1.yml --config tune0.yml
dqcd.py --runmode train --inputfiles theory_A_point_2.yml --config tune0.yml
dqcd.py --runmode train --inputfiles theory_A_point_3.yml --config tune0.yml


# --------------------
## Evaluate models

# Theory A: MVA conditionalized on all model points
dqcd.py --runmode eval --inputfiles theory_A_point_1.yml --config tune_ANY.yml
dqcd.py --runmode eval --inputfiles theory_A_point_2.yml --config tune_ANY.yml
dqcd.py --runmode eval --inputfiles theory_A_point_3.yml --config tune_ANY.yml

# Theory A: MVA trained per model point
dqcd.py --runmode eval --inputfiles theory_A_point_1.yml --config tune0.yml
dqcd.py --runmode eval --inputfiles theory_A_point_2.yml --config tune0.yml
dqcd.py --runmode eval --inputfiles theory_A_point_3.yml --config tune0.yml

