basic:
  active: true
  nbins:  70
  exclude_vals: [null, 0]

corrmat:
  active: false

contours: 
  active: false

MVA_output:
  active: true
  edges: 80

ROC:
  active: true

ROC_binned:
  active: false

MVA_2D:
  active: false
