# Github actions CI (continous integration) setup

name: icenet-install-test

on: [push]


jobs:
  icenet-install-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.5'

      ## Docs building
      - name: Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
          
          make -C docs/ clean
          make -C docs/ html
          touch docs/build/html/.nojekyll

      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/

      # ----------------------------------------------

      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v

      ## Install:
      - run: pip install -r requirements-travis-1
      - run: pip install -r requirements-travis-2

      ## Tests
      #- git clone git@github.com:mieskolainen/travis-stash.git
      - run: git clone https://github.com/mieskolainen/travis-stash.git
      - run: source tests/runme_trg.sh
      - run: source tests/runme_eid.sh
      - run: source tests/runme_brk.sh
