# Github actions CI (continous integration) setup

name: icenet-install-test

on: [push]

jobs:
  icenet-install-test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9.6'
      
      ## Install:
      - name: Install requirements
        run: |
          conda install -c nvidia cudatoolkit==11.3.1 cudnn==8.2.1
          conda install -c conda-forge cudatoolkit-dev
          pip install -r requirements.txt
      
      ## Docs building
      - name: Build docs
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build

          make -C docs/ clean
          make -C docs/ html
          touch docs/build/html/.nojekyll

      ## Release to gh-pages
      - name: Release docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/

      ## Tests
      - name: Run Deep Learning tests
        run: |
          git clone https://github.com/mieskolainen/travis-stash.git
          source tests/runme_trg.sh
          source tests/runme_eid.sh
          source tests/runme_brk.sh
