# Github actions CI (continous integration) setup

name: icenet-install-test

on: [push]

jobs:
  icenet-install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v

      # install:
      - run: pip install -r requirements-travis-1
      - run: pip install -r requirements-travis-2

      # script:
      #- pytest --cov
      - run: make -C docs/ clean
      - run: make -C docs/ html
      - run: touch docs/build/html/.nojekyll

      # Tests
      #- git clone git@github.com:mieskolainen/travis-stash.git
      - run: git clone https://github.com/mieskolainen/travis-stash.git
      - run: source tests/runme_trg.sh
      - run: source tests/runme_eid.sh
      - run: source tests/runme_brk.sh

      #deploy:
      #  - provider: pypi
      #    user: "__token__"
      #    password: $PYPI_TOKEN
      #    skip_existing: true
      #  - provider: pages:git
      #    verbose: true
      #    token: $GITHUB_TOKEN
      #    edge: true
      #    local_dir: ./docs/build/html/
      #    keep_history: true

      - name: Deploy
        uses: mieskolainen/icenet@v1
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
