# Github actions CI (continous integration) setup

name: icenet-install-test

on: [push]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  icenet-install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.5'

      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v

      ## Install:
      - run: pip install -r requirements-travis-1
      - run: pip install -r requirements-travis-2

      ## Tests
      #- git clone git@github.com:mieskolainen/travis-stash.git
      - run: git clone https://github.com/mieskolainen/travis-stash.git
      - run: source tests/runme_trg.sh
      - run: source tests/runme_eid.sh
      - run: source tests/runme_brk.sh

      ## Documentation for the webpage
      #- run: make -C docs/ clean
      #- run: make -C docs/ html
      #- run: touch docs/build/html/.nojekyll

      #- name: Set-up Node
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install
      #- run: npm run build
      #- run: npm test

      - name: Deploy
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: gh-pages
          force: true
          #build_dir: build
          directory: ./docs/build/html/

