# Github actions CI (continous integration) setup

name: icenet-install-test

on: [push]


jobs:
  icenet-install-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8.5'


      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/build/html/ # The folder the action should deploy.

      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v

      ## Install:
      - run: pip install -r requirements-travis-1
      - run: pip install -r requirements-travis-2

      ## Tests
      #- git clone git@github.com:mieskolainen/travis-stash.git
      - run: git clone https://github.com/mieskolainen/travis-stash.git
      - run: source tests/runme_trg.sh
      - run: source tests/runme_eid.sh
      - run: source tests/runme_brk.sh

      ## Documentation for the webpage
      #- run: make -C docs/ clean
      #- run: make -C docs/ html
      #- run: touch docs/build/html/.nojekyll

      #- name: Set-up Node
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '14'
      #- run: npm install
      #- run: npm run build
      #- run: npm test